export enum Colors  {
  theme = '#FFCC00',
  Regular = '#222222',
  frozen = '#ffffff',
  mintYellow = '#FFFEF1',
  bg_white = '#F5F6FB',
  fbColor = '#1877F2',
  grey = '#C5C7CA',
  green = '#27D045', 
  danger = '#D02727',
  text = "text",
  Active = "Active",
  Inactive = "Inactive",
  Active = "Active", 
};